### PR TITLE
Worked on updating view.php file

### PR DESCRIPTION
**Pull request by drachels**
Fixed all but one error (line 148) reported by codechecker for this file. If you want me too, I will continue to make codechecker recommended changes and push them to you. If you do want me to continue, please look at the copyright line on line 24 to make sure it is okay, or if it needs to be changed.

### CODE REVIEW

**Comment by donhinkelman** [comment]
Thanks drachels, for the pull request. Both Brendon and I are not coders, so before we merge the pull request, can you explain what problem this is fixing?

**Comment by drachels** [comment]
> Thanks drachels, for the pull request. Both Brendon and I are not coders, so before we merge the pull request, can you explain what problem this is fixing?

Right, for the most part each file in a Moodle plugin is supposed to have a bunch of boilerplate text at the start of the file that lists license and redistribution rules, along with what the particular file is there for. It lists the particular package, copyright holder and provides a link to the GNU GPL v3 license. I need to know who or what you would like listed as the copyright holder. Is it okay as shown in the view.php file? If I need to add Brendon, then I need to know his last name and email address, to be able to add and use it.

The reason there are so many files in this pull request is due to each file needing the end of lines fixed. They all need to be EOL Unix(LF).

I also fixed some dates in the /videoassessment/db/upgrade.php file. The dates should be ten digits long and somewhere in there at one point they became eleven digits long. All I did was remove one of the extra zeros from the last three of the digits that normally are used to indicate a change to the code made on the same day indicated by the first eight digits.

I will need to go back through and make sure I fixed all of the require_once('xxxx'); lines of code as the, parenthesis, are required.
I have also started to fix any array code as it needs to use, square brackets. e.g $courseopts = array(); needs to be rewritten as $courseopts = [];

**Comment by donhinkelman** [comment]
Hi drachels and thank you for all the commits. Brendon and team have contracted for our local Chieru programming team led by Yishe-san to handle all the issues raised by Moodle.org review team. They will make a branch on Monday, October 28th, 10am Japan time (01:00 am Monday Togo time). Yishe reviewed all your commits and thanks you for them. She wants to include all the commits of other fixes you want to make. If you have more, please make them in the next 35 hours and they will be included in the new version of Video Assessment Module which will be released and tested in late November. After checking the commits, Yishe san recommends that Brendon merge the pull request(s) at about 9am Japan time, and they will begin work.

**Comment by drachels** [comment]
Hi Don,
I will add what I can, but just got a request for help with my MooTyper plugin that might cut into my "play" time where I would normally do things like this. I will say, that the two most important things you could have them do is to install and use two plugins, local_codechecker and local_moodlecheck. These two Moodle debugging plugins will show a bunch of things that need to be fixed/changed, and are what I have been working from/with.

**Comment by donhinkelman** [comment]
Thank you, drachels, for your additional work. I will pass your advice on to Yishe and the Chieru development team to install and use two plugins, **local_codechecker** and **local_moodlecheck.** These two Moodle debugging plugins will continue the work you have done so far.

**Comment by BM373** [comment]
> Hi Don, I will add what I can, but just got a request for help with my MooTyper plugin that might cut into my "play" time where I would normally do things like this. I will say, that the two most important things you could have them do is to install and use two plugins, local_codechecker and local_moodlecheck. These two Moodle debugging plugins will show a bunch of things that need to be fixed/changed, and are what I have been working from/with.

Your contributions are much appreciated Al.  Thank you.

**Pull request merged**
